version: '3.11'

services:
  app:
    image: annachiriciuc07/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres_master
      - postgres_slave1
      - postgres_slave2
      - postgres_slave3
      - mongo_primary
      - mongo_secondary1
      - mongo_secondary2
      - mongo_secondary3
      - redis
    environment:
      - DATABASE_URL=postgres://master_user:master_password@postgres_master:5432/master_db
      - MONGO_URL=mongodb://mongo_primary:27017/content
      - REDIS_URL=redis://redis:6379/0

  postgres_master:
    image: annachiriciuc07/postgres_master:latest
    environment:
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: master_password
      POSTGRES_DB: master_db
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./init_master_slave.sh:/docker-entrypoint-initdb.d/init_master_slave.sh
    ports:
      - "5432:5432"

  postgres_slave1:
    image: annachiriciuc07/postgres_slave1:latest
    environment:
      POSTGRES_USER: replication_user
      POSTGRES_PASSWORD: replication_password
      POSTGRES_DB: slave_db1
      POSTGRES_MASTER_HOST: postgres_master
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - postgres_slave1_data:/var/lib/postgresql/data
      - ./init_master_slave.sh:/docker-entrypoint-initdb.d/init_master_slave.sh
    ports:
      - "5433:5432"

  postgres_slave2:
    image: annachiriciuc07/postgres_slave2:latest
    environment:
      POSTGRES_USER: replication_user
      POSTGRES_PASSWORD: replication_password
      POSTGRES_DB: slave_db2
      POSTGRES_MASTER_HOST: postgres_master
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - postgres_slave2_data:/var/lib/postgresql/data
      - ./init_master_slave.sh:/docker-entrypoint-initdb.d/init_master_slave.sh
    ports:
      - "5434:5432"

  postgres_slave3:
    image: annachiriciuc07/postgres_slave3:latest
    environment:
      POSTGRES_USER: replication_user
      POSTGRES_PASSWORD: replication_password
      POSTGRES_DB: slave_db3
      POSTGRES_MASTER_HOST: postgres_master
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - postgres_slave3_data:/var/lib/postgresql/data
      - ./init_master_slave.sh:/docker-entrypoint-initdb.d/init_master_slave.sh
    ports:
      - "5435:5432"

  mongo_primary:
    image: annachiriciuc07/mongo_primary:latest
    command: [ "mongod", "--bind_ip_all", "--dbpath=/data/db", "--oplogSize=100" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo_primary_data:/data/db

  mongo_secondary1:
    image: annachiriciuc07/mongo_secondary1:latest
    command: ["mongod", "--bind_ip_all", "--dbpath=/data/db", "--oplogSize=100"]
    ports:
      - "27018:27017"
    volumes:
      - mongo_secondary1_data:/data/db

  mongo_secondary2:
    image: annachiriciuc07/mongo_secondary2:latest
    command: ["mongod", "--bind_ip_all", "--dbpath=/data/db", "--oplogSize=100"]
    ports:
      - "27019:27017"
    volumes:
      - mongo_secondary2_data:/data/db

  mongo_secondary3:
    image: annachiriciuc07/mongo_secondary3:latest
    command: ["mongod", "--bind_ip_all", "--dbpath=/data/db", "--oplogSize=100"]
    ports:
      - "27020:27017"
    volumes:
      - mongo_secondary3_data:/data/db

  redis:
    image: annachiriciuc07/redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_master_data:
  postgres_slave1_data:
  postgres_slave2_data:
  postgres_slave3_data:
  mongo_primary_data:
  mongo_secondary1_data:
  mongo_secondary2_data:
  mongo_secondary3_data:
